name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: get node_modules cache
      uses: actions/upload-artifact@v1
      with:
        name: node_modules
        path: node_modules
    - name: yarn install
      run: yarn
    - name: restore node_modules cache
      uses: actions/download-artifact@v1
      with:
        name: node_modules
    - name: test
      run: yarn test
