name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run: yarn
    - name: test
      run: yarn test
    - name: build
      run: yarn build
    - name: upload dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
